name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node version to 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install
        run: npm ci

      - name: build
        run: npm run build:clean

      - name: test
        run: npm test

      - name: Check if working tree is clean
        run: git diff --exit-code

      - name: Publish to npm
        run: npm run publish-ci ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Generate Changelog
      #   run: npx changelogithub
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}